language: python
python:
  - "2.7.12"
# command to install dependencies
install:
  - pip install mysql-python --use-mirrors
  - pip install -r requirements.txt
# command to run tests
script:
  - python anqingtv.py